on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      tofu-version:
        required: true
        type: string
      run-tftest:
        required: true
        type: boolean

defaults:
  run:
    shell: bash

jobs:

  tftest:
    name: Test Tofu
    runs-on: ${{ inputs.runner }}
    if: inputs.run-tftest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/tofu-init
        with:
          tofu-version: ${{ inputs.tofu-version }}

      - run: tofu test
